package exceptionhandling;

public class TryCatchFinally {
	
	public static void main(String[] args) {
		
		try
		{
			int i = 10;
			int j = 0;
			int k = i/j;
			
		}

		finally
		{
			System.out.println("Finally is executing");
			
		}
		
		
		
		
		
	}

}
